deploy:
  stage: Deploy
  only:
    refs:
      - master
      - develop
  variables:
    APP_TYPE: <APP_TYPE_VALUE>
  script:
    - |
      # Defining AWS Account
      if [[ "${CI_BUILD_REF_NAME}" == "develop" ]];then
        export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID_DEV}"
        export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY_DEV}"
      fi

      if [[ "${CI_BUILD_REF_NAME}" == "master" ]];then
        export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID_STAGING}"
        export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY_STAGING}"
      fi

      # Implement lambda deployment in here!
