dns-creation:
  stage: DNSCreation
  only:
    refs:
      - master
      - develop
  script:
    - |
      function terraform_run() {
        cd ${CI_PROJECT_DIR}/.gitlab-ci/automations/dns

        rm -rf .terraform*
        aws eks update-kubeconfig --name "${EKS_CLUSTER}"

        if [[ -z "${DOMAIN_PREFIX}" ]]; then
          sh pre-recipe.sh  "${K8S_NAMESPACE}" "${CI_PROJECT_NAME}"
        else
          sh pre-recipe.sh  "${K8S_NAMESPACE}" "${DOMAIN_PREFIX}"
        fi

        terraform init -backend-config="bucket=terraform-state-${K8S_NAMESPACE}" -backend-config="key=dns-creation-${CI_PROJECT_NAME}"
        terraform plan -out=tfplan -input=false && terraform apply -input=false tfplan

        rm -rf .terraform*
      }

      if [[ "${CI_BUILD_REF_NAME}" == "develop" ]];then
        K8S_NAMESPACE="development"
        export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID_DEV}"
        export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY_DEV}"

        terraform_run
      fi

      if [[ "${CI_BUILD_REF_NAME}" == "master" ]];then
        K8S_NAMESPACE="staging"
        export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID_STAGING}"
        export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY_STAGING}"

        terraform_run

        K8S_NAMESPACE="production"
        export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID_PRODUCTION}"
        export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY_PRODUCTION}"

        terraform_run
      fi
