promote-to-production:
  stage: PromoteToProduction
  only:
    refs:
      - master
  variables:
    APP_TYPE: <APP_TYPE_VALUE>
  script:
    - |
      if [[ "${CI_BUILD_REF_NAME}" == "master" ]];then
        readonly K8S_NAMESPACE="production"
        export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID_PRODUCTION}"
        export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY_PRODUCTION}"
      fi

      # Setting up DOCKER_TAG variable
      readonly TAG="${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_BUILD_REF:0:8}"
      readonly DOCKER_TAG=$(echo "${TAG}" | sed 's/\//\\\//g') # Escaping forward slashes

      # Generating credentials to access EKS.
      aws eks update-kubeconfig --name "${EKS_CLUSTER}"

      # Replacing variables into service.yml
      sed -i "s/<APP_NAME>/${CI_PROJECT_NAME}/g" .k8s/base/service.yml
      sed -i "s/<K8S_NAMESPACE>/${K8S_NAMESPACE}/g" .k8s/base/service.yml

      # Replacing variables into configmap.yml
      sed -i "s/<APP_NAME>/${CI_PROJECT_NAME}/g" .k8s/base/configmap.yml
      sed -i "s/<K8S_NAMESPACE>/${K8S_NAMESPACE}/g" .k8s/base/configmap.yml

      # Replacing variables into deployment.yml
      sed -i "s/<APP_TYPE>/${APP_TYPE}/g" .k8s/base/deployment.yml
      sed -i "s/<DOCKER_TAG>/${DOCKER_TAG}/g" .k8s/base/deployment.yml
      sed -i "s/<APP_NAME>/${CI_PROJECT_NAME}/g" .k8s/base/deployment.yml
      sed -i "s/<K8S_NAMESPACE>/${K8S_NAMESPACE}/g" .k8s/base/deployment.yml
      sed -i "s/<CONTAINER_NAME>/${CI_PROJECT_NAME}/g" .k8s/base/deployment.yml
      sed -i "s/<IMAGE_PULL_SECRETS>/${CI_PROJECT_NAME}/g" .k8s/base/base/deployment.yml

      # Replaceing variables into horizontal-pod-autoscaler.yml
      sed -i "s/<APP_NAME>/${CI_PROJECT_NAME}/g" .k8s/base/horizontal-pod-autoscaler.yml
      sed -i "s/<K8S_NAMESPACE>/${K8S_NAMESPACE}/g" .k8s/base/horizontal-pod-autoscaler.yml

      # Applying base resources
      kubectl apply -f .k8s/base/

      # NOTE: Uncomment the following line in case you are using Kustomize.
      # kubectl apply -k ".k8s/worker/overlays/${K8S_NAMESPACE}"
